source "https://github.com/CocoaPods/Specs.git"
platform :ios, "10.0"
use_frameworks!
target "userLocation" do
pod 'Firebase/Core', '4.0.4'
pod 'Firebase/Database', '4.0.0'
pod 'Firebase/Auth', '4.0.0'
pod 'Firebase/Messaging', '2.0.0'
pod 'Onboard', '2.3.1'
end
